ARG version 
FROM almalinux:${version:-9}
ARG course="Docker" \
    trainer="Time" \
    duration="responsibility"
RUN echo "course is : ${course}, and the trainer is ${trainer}, and duration is : ${duration} "